### ISSUE TITLE
금전 표시를 할 때, 콤마는 어떻게 하면 넣을 수 있을까요?

### ISSUE THREAD

**Issue by mocona** [ProjectInTheClass/SaveDonDon#14]
공통 주제.
금전 표시를 할 때, 콤마는 어떻게 하면 넣을 수 있을까요?

담당자 할당 후 찾아서 적용해 보세요~!

커밋도 하시고~

**Comment by dream7739** [comment]
했습니당 ㅎ ㅔ ㅎ ㅔ
