### ISSUE TITLE
[ASAP] gitignore 에 macOS 항목도 추가해 넣으세요.

### ISSUE THREAD

**Issue by mocona** [ProjectInTheClass/SaveDonDon#22]
https://github.com/github/gitignore/blob/master/Global/macOS.gitignore

위 항목이 .gitignore 에 누락되었어요.

추가해 주세요~!

AS SOON AS POSSIBLE!

**Comment by dream7739** [comment]
했습니당

**Comment by mocona** [comment]
잘해쓰, 꼬부기!
